### PR TITLE
update for fido2 1.0 api changes; fixes #233

### LINKED ISSUE #223: Fails to run with cryptography==37.0.2
Current release fails to work with `cryptography==37.0.2`

#### Workaround
```
 pip3 install cryptography==36.0.2
```

### LINKED ISSUE #233: pynitrokey on a fresh install, problem with the latest version reproduced locally with pipx on Ubuntu 22.04:
```
root@1fc924ae3e76:/# ~/.local/bin/nitropy 
Traceback (most recent call last):
  File "/root/.local/bin/nitropy", line 5, in <module>
    from pynitrokey.cli import main
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/cli/__init__.py", line 19, in <module>
    import pynitrokey.fido2.operations
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/fido2/__init__.py", line 10, in <module>
    from pynitrokey.fido2.client import NKFido2Client
  File "/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/pynitrokey/fido2/client.py", line 26, in <module>
    from fido2.ctap1 import CTAP1
ImportError: cannot import name 'CTAP1' from 'fido2.ctap1' (/root/.local/pipx/venvs/pynitrokey/lib/python3.10/site-packages/fido2/ctap1.py)
root@1fc924ae3e76:/# history 
    1  apt update
    2  apt install pipx
    3  pipx install pynitrokey
    7  ~/.local/bin/nitropy 
    ```

### PR DESCRIPTION
**Pull request by daringer**
Updating fido2 module to match version 1.0 `fido2` API changes

## Changes
* some symbol renaming (`CTAPX` to `CtapX`)
* `ClientPin` usage instead of `client.client_pin` 

## Checklist

- [x] tested with Python3.6
- [x] run `make check` or `make fix` for the formatting check
- [x] signed commits
- [ ] updated documentation (e.g. parameter description, inline doc, docs.nitrokey)
- [ ] added labels

## Test Environment and Execution

- OS: Arch Linux
- device's model: NK FIDO2
- device's firmware version: 2.4.0

Fixes #233

### CODE REVIEW

**Review by szszszsz — APPROVED** [review]

**Review by robin-nitrokey — APPROVED** [review]

**Comment by daringer** [comment]
> ```
> $ make check
> pynitrokey/cli/fido2.py Imports are incorrectly sorted and/or formatted
> ```

fixed (I lied and did not run `make fix` but just `black` directly) :D
